### PR TITLE
Remove saas codelab implementation

### LINKED ISSUE #41: Remove support for Codelab
From code and docs

### PR DESCRIPTION
**Pull request by caddac**
resolves #41

### CODE REVIEW

**Comment by apgiorgi** [comment]
Sweet! LGTM. Thanks!

**Review by apgiorgi — APPROVED** [review]
LGTM

**Review by venotar — APPROVED** [review]
Don't see any obvious concerns

**Comment by JoshuaFox** [comment]
LGTM

**Pull request merged**
